# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_FSK_CC1120) += fsk-cc1120.o
fsk-cc1120-y := cc1120.o

obj-$(CONFIG_FSK_MRF89XA) += fsk-mrf89xa.o
fsk-mrf89xa-y := mrf89xa.o

obj-$(CONFIG_FSK_NRF24L01P) += fsk-nrf24l01p.o
fsk-nrf24l01p-y := nrf24l01p.o

obj-$(CONFIG_FSK_SI443X) += fsk-si443x.o
fsk-si443x-y := si443x.o

obj-$(CONFIG_FSK_S2LP) += fsk-s2lp.o
fsk-s2lp-y := s2-lp.o
