# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_LORAWAN_GMX_LR1) += lorawan-gmx-lr1.o
lorawan-gmx-lr1-y += gmxlr1.o

obj-$(CONFIG_LORAWAN_RM1XX) += lorawan-rm1xx.o
lorawan-rm1xx-y += rm1xx.o
